// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/editor": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/editor" | "/privacy-policy" | "/*";
  };
  "routes/editor._app.tsx": {
    id: "routes/editor._app";
    page: "/editor";
  };
  "routes/editor._app._index.tsx": {
    id: "routes/editor._app._index";
    page: "/editor";
  };
  "routes/_shell.tsx": {
    id: "routes/_shell";
    page: "/privacy-policy" | "/" | "/*";
  };
  "routes/_shell.privacy-policy.tsx": {
    id: "routes/_shell.privacy-policy";
    page: "/privacy-policy";
  };
  "routes/_shell._index.tsx": {
    id: "routes/_shell._index";
    page: "/";
  };
  "routes/_shell.$.tsx": {
    id: "routes/_shell.$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/editor._app": typeof import("./src/routes/editor._app.tsx");
  "routes/editor._app._index": typeof import("./src/routes/editor._app._index.tsx");
  "routes/_shell": typeof import("./src/routes/_shell.tsx");
  "routes/_shell.privacy-policy": typeof import("./src/routes/_shell.privacy-policy.tsx");
  "routes/_shell._index": typeof import("./src/routes/_shell._index.tsx");
  "routes/_shell.$": typeof import("./src/routes/_shell.$.tsx");
};